[GENERAL]
Version=1

[DISPLAY]
;GPUAdapterInfo => Video adapter hash DeviceInstanceID
;GPUAdapterSelectMode => 0 select by index (GPUAdapter) / 1 select by GPUAdapterInfo
;InitialWindowPositionX/Y => -1 for centering
;FPSLimit => Limit the game's fps. Minimum of 30fps. Anything below will disable the fps limit.
;NVReflex. 0 : Disable, 1 : ReflexOn, 2 - ReflexWithBoost
;NVReflexIndicator => Enables the in-game latency metrics indication.
;Console => Enables the in-game console which is mapped to `/~. Will only work if the key is not already mapped.
GPUInfo=-733318085
GPUAdapter=0
GPUAdapterInfo=-1215198245
GPUAdapterSelectMode=0
InitialWindowPositionX=8
InitialWindowPositionY=31
Brightness=60.000000
FPSLimit=0
NVReflex=0
NVReflexIndicator=0
Console=0

[HARDWARE_INFO]
GPUVendor=AMD
GPUDeviceId=0x7590
GPUSubSysId=0x86011eae
GPUDedicatedMemoryMB=16253
GPUScore=26940.000000
GPUScoreConf=0.812477
SystemMemoryMB=32692
CPUScore=9438.293945
HardwareNotificationEnable=1

[DISPLAY_SETTINGS]
;ResolutionXXX    => 0 for autodetection
;RefreshRate      => 0 will let DirectX pick it
;WindowMode       => 0 fullscreen / 1 windowed / 2 borderless
;AspectRatio      => 0 display / 1 resolution / 2..N as options
;VSync            => 0 disabled / 1 frame / 2 frames
;UseLetterbox     => 0 disabled / 1 enabled
;DefaultFOV       => Default vertical field of view (degrees)
;UseAmdAGS => Enables usage of AMD AGS library for additional info in crash reports
;VulkanWhitelistedLayers => Semicolon separated list, with all the Vulkan layers you want to enable, like VK_LAYER_VALVE_steam_fossilize;VK_LAYER_RTSS
Monitor=0
ResolutionWidth=1920
ResolutionHeight=1080
RefreshRate=239.964005
WindowMode=2
AspectRatio=3
VSync=0
MaxGPUBufferedFrame=1
UseLetterbox=0
DefaultFOV=90.000000
EnableAMDMultiDraw=1
EnableIntelMultiDraw=1
UseAmdAGS=1
VulkanWhitelistedLayers=VK_LAYER_OW_OBS_HOOK;VK_LAYER_OW_OVERLAY

[QUALITY]
OverallQualityLevelName=Custom

[CUSTOM_QUALITY]
AntiAliasing=2
Atmospheric=-1
Geometry=4
Lighting=0
Shadow=1
Sharpness=10
Texture=0
VFX=0
TextureFiltering=0
Reflection=0
AO=0
LensEffects=0
DOF=0
AdaptiveRenderScalingTargetFPS=0
RenderScalingFactor=0
DLSSPerfQual=0
FSR2PerfQual=0
FSRPerfQual=0
TextureStreaming=0
TextureVRAMLimit=2

[READ_ONLY]
EngineSettingsVersion=2
DefaultValuesVersion=12

[INPUT]
RawInputMouseKeyboard=1
InvertAxisY=0
InvertMouseAxisY=0
Rumble=0
YawSensitivity=50
PitchSensitivity=35
DeadzoneLeftStick=5
DeadzoneRightStick=5
DeadzoneTriggerLeft=10
DeadzoneTriggerRight=10
DeadzoneSwitchInputStick=30
ControllerStickRotationCurve=1
MouseSensitivity=50
MouseYawSensitivity=14
MousePitchSensitivity=14
MouseSensitivityMultiplierUnit=0.020000
MouseScroll=1
XFactorAiming=0.020000
ToggleAim=0
ToggleAimGamepad=0
ToggleLean=1
ToggleSprint=1
ToggleCrouch=1
ToggleProne=1
ToggleWalk=0
ToggleDroneBoost=0
ToggleGadgetDeploymentGamepad=1
ToggleGadgetDeploymentKeyboard=1
AimDownSights=50
ADSGamepadUseSpecific=1
ADSGamepadSensitivityGlobal=50
ADSGamepadSensitivity1x=30
ADSGamepadSensitivity1xHalf=58
ADSGamepadSensitivity2x=59
ADSGamepadSensitivity2xHalf=40
ADSGamepadSensitivity3x=60
ADSGamepadSensitivity4x=60
ADSGamepadSensitivity5x=61
ADSGamepadSensitivity12x=93
ADSGamepadMultiplierUnit=0.020000
AdvancedGamepadOptions=0
GamepadHorizontalFullTiltBoostModifier=50
GamepadVerticalFullTiltBoostModifier=50
FullTiltBoostRampupDelay=0.000000
GamepadFullTiltBoostRampupTime=0.350000
ADSGamepadHorizontalFullTiltBoostModifier=20
ADSGamepadVerticalFullTiltBoostModifier=15
ADSFullTiltBoostRampupDelay=0.250000
ADSGamepadFullTiltBoostRampupTime=1.000000
OuterDeadzoneRightStick=0
GamepadLookDampeningTime=0.000000
AimDownSightsMouse=64
ADSMouseUseSpecific=1
ADSMouseSensitivityGlobal=50
ADSMouseSensitivity1x=51
ADSMouseSensitivity1xHalf=45
ADSMouseSensitivity2x=50
ADSMouseSensitivity2xHalf=60
ADSMouseSensitivity3x=60
ADSMouseSensitivity4x=70
ADSMouseSensitivity5x=77
ADSMouseSensitivity12x=86
ADSMouseMultiplierUnit=0.020000
ControlSchemeIndex=0
ControllerInputDevice=0

[AUDIO]
;Dynamic Range mode: (0) Hi-Fi, (1) TV, (2) Night Mode
;VoiceChatCaptureMode => 0 Auto / 1 Manual / 2 Push to talk
SubtitleType=1
Subtitle=0
MasterVolume=89.000000
MenuMusicVolume=0.000000
InGameMusicVolume=0.000000
MenuSFXVolume=56.000000
InGameSFXVolume=100.000000
VoiceVolume=0.000000
DynamicRangeMode=2
MonoOutput=0
VoiceChatPlaybackLevel=68
VoiceChatCaptureThresholdV2=12
VoiceChatCaptureMode=2
VoiceChatCaptureLevel=100
Mute=0
VoiceChatMuteAll=0
VoiceChatTeamOnly=1
AudioInputVoiceChatDevice=1757792678
AudioOutputVoiceChatDevice=2027604414
AudioOutputDevice=2027604414

[GAMEPLAY]
GameplayPingEnable=1

[ACCESSIBILITY]
AccessibilityColorMode=1
PositiveColorIndex=0
NegativeColorIndex=1
ObjectiveColorIndex=0
PingColorIndex=0
TeamColorAllyIndex=0
TeamColorEnemyIndex=2
StunVFXMode=1
TinnitusSFXMode=1
HearingFatigueAid=1

[ONLINE]
;DataCenterHint => 
;    default (ping based)
;    playfab/australiaeast
;    playfab/brazilsouth
;    playfab/centralus
;    playfab/eastasia
;    playfab/eastus
;    playfab/japaneast
;    playfab/northeurope
;    playfab/southafricanorth
;    playfab/southcentralus
;    playfab/southeastasia
;    playfab/uaenorth
;    playfab/westeurope
;    playfab/westus

;
;if UseProxyAutoDiscovery is set to true, http_proxy or https_proxy or all_proxy and no_proxy are going to be looked up and used for all http calls
DataCenterHint=eucentral
UseProxyAutoDiscovery=1

